In [1]:
import numpy as np

## Arrays
### Task
You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

In [8]:
def arrays(arr):
    return np.array(arr[::-1],float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape

Task

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

In [31]:
my_array = np.array(input().split(),int)
reshape_array = my_array.reshape(3,3)
print(reshape_array)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten
Task <br> 

You are given a NXM integer array matrix with space separated elements (N = rows and M = columns). <br> 
Your task is to print the transpose and flatten results.

In [49]:
n,m = map(int,input().split())

my_array = np.array([input().strip().split(' ') for i in range(n)],int)
transpose_array = np.transpose(my_array)
flatten_array = my_array.flatten()
print(transpose_array)
print(flatten_array)

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Concatenate
Task<br>
You are given two integer arrays of size N X P and M X P (N & M are rows, and P is the column). Your task is to concatenate the arrays along axis 0.

In [55]:
n,m,p = map(int,input().split())
my_array_n = np.array([input().strip().split(' ') for i in range(n)],int)
my_array_m = np.array([input().strip().split(' ') for i in range(m)],int)
concatenate_array = np.concatenate((my_array_n,my_array_m),axis=0)
print(concatenate_array)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones

Task<br>
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

In [57]:
my_array = np.array(input().strip().split(' '),int)
zeros_array = np.zeros((my_array),dtype=np.int)
ones_array = np.ones((my_array),dtype=np.int)
print(zeros_array)
print(ones_array)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Eye and Identity

Task :<br>
Your task is to print an array of size N*M with its main diagonal elements as 1's and 0's everywhere else.

In [62]:
np.set_printoptions(legacy = '1.13')
n,m = map(int,input().split(' '))
eye_matrix = np.eye(n,m,k=0)
print(eye_matrix)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Array Mathematics
Task :<br>
You are given two integer arrays, A and B of dimensions NXM.<br>
Your task is to perform the following operations:<br>
Add ( A + B)<br>
Subtract ( A - B)<br>
Multiply ( A * B)<br>
Integer Division (A / B)<br>
Mod (A % B)<br>
Power (A ** B)

In [68]:
n,m = map(int,input().split(' '))
my_array_n = np.array([input().strip().split(' ') for i in range(n)],int)
my_array_m = np.array([input().strip().split(' ')for i in range(n)],int)
addition = np.add(my_array_n,my_array_m)
subtraction = np.subtract(my_array_n,my_array_m)
multiplication = np.multiply(my_array_n,my_array_m)
division = np.floor_divide(my_array_n,my_array_m)
mod_array = np.mod(my_array_n,my_array_m)
power_array = np.power(my_array_n,my_array_m)
print(addition)
print(subtraction)
print(multiplication)
print(division)
print(mod_array)
print(power_array)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Floor, Ceil and Rint
Task :<br>
You are given a 1-D array, A. Your task is to print the floor, celi and rint of all the elements of A.

In [75]:
np.set_printoptions(legacy = '1.13')

my_array = np.array(input().strip().split(' '),float)
my_array_floor = np.floor(my_array)
my_array_ceil = np.ceil(my_array)
my_array_rint = np.rint(my_array)
print(my_array_floor)
print(my_array_ceil)
print(my_array_rint)

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Sum and Prod
Task :<br>
You are given a 2-D array with dimensions NXM.<br>
Your task is to perform the sum tool over axis 0 and then find the product of that result. 

In [81]:
n,m = map(int,input().split(' '))
my_array = np.array([input().strip().split(' ') for i in range(n)],int)
sum_my_array = np.sum(my_array,axis=0)
prod_my_array = np.prod(sum_my_array)
print(prod_my_array)

2 2
1 2
3 4
24


## Min and Max
Task<br>
You are given a 2-D array with dimensions N X M.<br>
Your task is to perform the min function over axis 1 and then find the max of that.

In [86]:
n,m = map(int,input().split(' '))
my_array = np.array([input().strip().split(' ') for i in range(n)],int)
min_my_array = np.min(my_array,axis=1)
max_my_array = np.max(min_my_array)
print(max_my_array)

4 2
2 5
3 7
1 3
4 0
3


## Mean, Var, and Std

Task<br>
You are given a 2-D array of size NxM. <br>
Your task is to find:<br>
1. The mean along axis 1 <br>
2. The var along axis 0<br>
3. The std along axis none

In [90]:
n,m = map(int,input().split( ))
my_array = np.array([input().strip().split( ) for i in range(n)],int)
mean_array = np.mean(my_array, axis = 1)
var_array = np.var(my_array,axis = 0)
std_array = round(np.std(my_array,axis = None),11)
print(mean_array)
print(var_array)
print(std_array)

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## Dot and Cross
Task<br>
You are given two arrays A and B. Both have dimensions of NxN. <br>
Your task is to compute their matrix product.

In [93]:
n = int(input())
a_array = np.array([input().strip().split() for i in range(n)],int)
b_array = np.array([input().strip().split() for i in range(n)],int)
print(np.dot(a_array,b_array))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## Inner and Outer
Task<br>
You are given two arrays: A and B.<br>
Your task is to compute their inner and outer product.

In [96]:
a_array = np.array(input().strip().split(),int)
b_array = np.array(input().strip().split(),int)
print(np.inner(a_array,b_array))
print(np.outer(a_array,b_array))

0 1
2 3
3
[[0 0]
 [2 3]]


## Polynomials
Task<br>
You are given the coefficients of a polynomial P.<br>
Your task is to find the value of P at point x.

In [102]:
p_coeff = np.array(input().split(),float)
x = float(input())
print(np.polyval(p_coeff,x))

1 .1 2 3
0
3.0


## Linear Algebra
Task<br>
You are given a square matrix  with dimensions X. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.

In [104]:
n = int(input())
a_array = np.array([input().split() for i in range(n)],float)
result = round(np.linalg.det(a_array),2)
print(result)

2
1.1 1.1
1.1 1.1
0.0
